# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agregar_movimientos.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(230, 300)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(40, 10, 142, 267))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pb_seleccion_movimiento = QtWidgets.QPushButton(self.widget)
        self.pb_seleccion_movimiento.setObjectName("pb_seleccion_movimiento")
        self.verticalLayout.addWidget(self.pb_seleccion_movimiento)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.le_x = QtWidgets.QLineEdit(self.widget)
        self.le_x.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_x.setObjectName("le_x")
        self.gridLayout.addWidget(self.le_x, 1, 0, 1, 1)
        self.le_delay = QtWidgets.QLineEdit(self.widget)
        self.le_delay.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_delay.setText("")
        self.le_delay.setObjectName("le_delay")
        self.gridLayout.addWidget(self.le_delay, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.le_y = QtWidgets.QLineEdit(self.widget)
        self.le_y.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_y.setText("")
        self.le_y.setObjectName("le_y")
        self.gridLayout.addWidget(self.le_y, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.le_z = QtWidgets.QLineEdit(self.widget)
        self.le_z.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_z.setObjectName("le_z")
        self.gridLayout.addWidget(self.le_z, 5, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.pb_agregar_movimiento = QtWidgets.QPushButton(self.widget)
        self.pb_agregar_movimiento.setObjectName("pb_agregar_movimiento")
        self.verticalLayout_2.addWidget(self.pb_agregar_movimiento)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Agregar movimientos"))
        self.label.setText(_translate("Dialog", "Movimiento"))
        self.pb_seleccion_movimiento.setText(_translate("Dialog", "Mover a"))
        self.label_2.setText(_translate("Dialog", "X"))
        self.label_5.setText(_translate("Dialog", "Delay [ms]"))
        self.label_3.setText(_translate("Dialog", "Y"))
        self.label_4.setText(_translate("Dialog", "Z"))
        self.pb_agregar_movimiento.setText(_translate("Dialog", "Agregar"))
