# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python/ui/gestionar_cobots.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(373, 232)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 351, 211))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.lw_cobots_guardados = QtWidgets.QListWidget(self.widget)
        self.lw_cobots_guardados.setObjectName("lw_cobots_guardados")
        self.gridLayout.addWidget(self.lw_cobots_guardados, 1, 0, 2, 2)
        self.te_descripcion_cobot = QtWidgets.QTextEdit(self.widget)
        self.te_descripcion_cobot.setObjectName("te_descripcion_cobot")
        self.gridLayout.addWidget(self.te_descripcion_cobot, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 2, 2, 1)
        self.pb_cargar_cobot = QtWidgets.QPushButton(self.widget)
        self.pb_cargar_cobot.setObjectName("pb_cargar_cobot")
        self.gridLayout.addWidget(self.pb_cargar_cobot, 3, 0, 1, 1)
        self.pb_borrar_cobot = QtWidgets.QPushButton(self.widget)
        self.pb_borrar_cobot.setObjectName("pb_borrar_cobot")
        self.gridLayout.addWidget(self.pb_borrar_cobot, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Cobots guardados"))
        self.label_2.setText(_translate("Dialog", "Descripción"))
        self.pb_cargar_cobot.setText(_translate("Dialog", "Cargar cobot"))
        self.pb_borrar_cobot.setText(_translate("Dialog", "Borrar cobot"))
